# Exported from Render on 2025-06-23T16:12:32Z
services:
- type: web
  name: agenda_webpy
  runtime: python
  repo: https://github.com/salvadorhm/agenda_webpy
  plan: free
  envVars:
  - key: PYTHON_VERSION
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 main.py
  autoDeployTrigger: commit
  rootDir: agenda
version: "1"